name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup npm package
        run: npm init -y && npm install
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with: 
          start: npm start
