name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup npm package
        run: sudo apt-get install -y npm
#         run: npm init -y && npm install
      - name: Cypress.io
        uses: cypress-io/github-action@v4
        with:
         command: npx cypress run
         browser: chrome
    #------------------
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: pwd
#         run: |
#           pwd
#           ls
#       - name: Cypress run
#         uses: cypress-io/github-action@v5
#         with:
#           project: ./newrepo/newrepo/cypress
#---------------------------------------------------
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Install node
#         uses: actions/setup-node@v2
#         with:
#            node-version: '14'
#       - name: Install dependencies
#         run: npm install
#       - name: current working directory
#         run:  pwd
#       - name: content
#         run:  ls
#       - name: Cypress run
#         uses: cypress-io/github-action@v2
     

                  # with: 
                  #   start: npm start
#       - name: Cypress i
#         run: npm install cypress --save-dev
#       - name: Cypress.io
#         uses: cypress-io/github-action@v4
#         with: 
#           command: npx cypress open
#           browser: chrome
